package com.example.demo.domain.statusEnums;

public enum TestRequestRecordStatus {
    TEST_INITIATED,
    TESTS_ITEMS_SELECTED,
    ADDRESS_SELECTED,
    TEST_DELIVERED,
    PHLEBOTOMIST_ASSIGNED,
    WAITING_TO_BE_CONFIRMED,
    CONFIRMED,
    TIME_SELECTED,
    WAITING_FOR_PAYMENT,
    PAYMENT_DONE
}