package com.example.demo.domain.statusEnums;

public enum TestRequestRecordStatus {
    TEST_INITIATED,
    TESTS_ITEMS_SELECTED,
    ADDRESS_SELECTED,
    TESTS_CONFIRMD,
    LAB_SELECTED,
    INFO_CONFIRMED,
    TIME_SELECTED_WAITING_FOR_PHLEBOTOMIST,
    PHLEBOTOMIST_ASSIGNED,
    WAITING_FOR_PAYMENT,
    PAYMENT_DONE,
    TEST_DELIVERED
}